In [1]:
import numpy as np

In [2]:
import random 

In [3]:
np.random.random(1)

array([0.97288947])

In [4]:
np.random.random((3,3))

array([[0.51537611, 0.6893358 , 0.83056964],
       [0.42932661, 0.28017171, 0.97354701],
       [0.56278276, 0.02585004, 0.50448771]])

In [9]:
np.random.randint(1,5)

2

In [10]:
np.random.randint(1,9,(4,4))

array([[4, 3, 2, 4],
       [4, 1, 5, 6],
       [4, 3, 7, 3],
       [3, 1, 2, 4]])

In [11]:
np.random.randint(1,9,(2,4,4))

array([[[8, 7, 3, 5],
        [1, 5, 3, 3],
        [5, 3, 6, 8],
        [1, 6, 6, 3]],

       [[6, 2, 1, 8],
        [1, 6, 8, 6],
        [4, 2, 6, 2],
        [3, 1, 5, 5]]])

In [12]:
np.random.seed(10)
np.random.randint(1,9,(4,4))

array([[2, 6, 5, 8],
       [1, 2, 4, 5],
       [2, 6, 1, 6],
       [2, 3, 1, 2]])

In [14]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [15]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [16]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [17]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [18]:
x=[1,2,3,4]
np.random.choice(x)

1

In [19]:
for i in range(20):
    print(np.random.choice(x))

1
1
2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2


In [20]:
x


[1, 2, 3, 4]

In [21]:
np.random.permutation(x)

array([1, 2, 4, 3])

In [22]:
np.random.permutation(x)

array([2, 3, 4, 1])