In [1]:
import numpy as np

In [2]:
mx_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])

In [3]:
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [7]:
mx_1s = np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [8]:
mx_1s.dtype

dtype('float64')

In [9]:
mx_1s = np.ones((2,4))

In [10]:
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.zeros((2,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.zeros((2,4),dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((2,4),dtype=bool)

array([[False, False, False, False],
       [False, False, False, False]])

In [16]:
np.zeros((2,4),dtype=str)

array([['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [17]:
np.empty((3,4))

array([[1.41712958e-311, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 1.93342776e-076, 3.37996079e-057,
        5.99249575e-038],
       [3.27802365e+179, 1.70382505e-051, 4.46975737e-062,
        2.35825268e+184]])

In [19]:
np.empty((2,3),dtype=int)

array([[-737287712,        667,          0],
       [         0,     131074,    6029363]])