# NumPy Function:

In [1]:
import numpy as np

## arange()

In [2]:
#np.arange(start,end,steps)

ar_1d = np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
odd_ar = np.arange(1,13,2)
print(odd_ar)

[ 1  3  5  7  9 11]


## linspace()

In [4]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

## reshape()

In [7]:
ar_2d = ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [8]:
ar_3d = ar_1d.reshape(2,3,2)

In [9]:
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


## ravel()

In [10]:
ar_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## flatten()

In [12]:
ar_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## transpose() or .T

In [14]:
ar_3d.transpose()

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [15]:
ar_3d.T

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])